# https://taskfile.dev
version: '3'
vars:
  IMAGENAME: sgaunet/alpine-sshd

tasks:
  default:
    cmds:
      - docker build -t {{.IMAGENAME}}:latest .
    # silent: true

  push:
    cmds:
      - docker push {{.IMAGENAME}}:latest
    
  test:
    deps:
      - default
    cmds:
      - venom run testsuite-docker.yml --output-dir log --stop-on-failure
    