# https://taskfile.dev
version: '3'
vars:
  IMAGENAME: sgaunet/alpine-sshd

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the docker image"
    cmds:
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t {{.IMAGENAME}}:latest .
      - docker pull {{.IMAGENAME}}:latest

  tests:
    desc: "Run the tests"
    dir: tests
    deps:
      - build
    cmds:
      - venom run testsuite-docker.yml --output-dir log --stop-on-failure
