# https://taskfile.dev
version: '3'
vars:
  IMAGENAME: sgaunet/alpine-sshd

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the docker image"
    cmds:
      - docker build -t {{.IMAGENAME}}:latest .
    # silent: true

  push:
    desc: "Push the docker image"
    cmds:
      - docker push {{.IMAGENAME}}:latest
    
  test:
    desc: "Run the tests"
    deps:
      - default
    cmds:
      - venom run testsuite-docker.yml --output-dir log --stop-on-failure
    