apiVersion: v1
kind: Service
metadata:
  name: svc-alpine-sshd
  namespace: prodautos
spec:
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
  type: NodePort
  selector:
    app: "alpine-sshd"
