name: publish docker image
on: push

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build/Push image ghcr.io/sgaunet/alpine-sshd:latest
        shell: /usr/bin/bash {0}
        run: |
          docker buildx build . --platform linux/amd64,linux/arm64 --push -t ghcr.io/sgaunet/alpine-sshd:latest

          # get tags of current commit
          tag=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
          if [ ! -z "$tag" ]; then
            echo "docker buildx build . --platform linux/amd64,linux/arm64 --push -t ghcr.io/sgaunet/alpine-sshd:$tag"
            docker buildx build . --platform linux/amd64,linux/arm64 --push -t ghcr.io/sgaunet/alpine-sshd:$tag
          fi
      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Tag and Push image to docker registry
        shell: /usr/bin/bash {0}
        run: |
            docker buildx build . --platform linux/amd64,linux/arm64 --push -t sgaunet/alpine-sshd:latest
            # get tags of current commit
            tag=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
            if [ ! -z "$tag" ]; then
              echo "docker buildx build . --platform linux/amd64,linux/arm64 --push -t sgaunet/alpine-sshd:$tag"
              docker buildx build . --platform linux/amd64,linux/arm64 --push -t sgaunet/alpine-sshd:$tag
            fi